FROM python:3.13-slim

RUN apt-get update && apt-get install -y \
    curl \
    bash \
    ca-certificates \
    libffi-dev \
    build-essential \
    && update-ca-certificates

WORKDIR /usr/src/app

COPY ./backend/requirements.txt ./requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY --chmod=0755 ./backend .

CMD ["sh", "./backend-entrypoint.sh"]
